### ISSUE TITLE
New website todo

### ISSUE THREAD

**Issue by shazow** [vipnode/vipnode.org#17]
These are not blocking the soft launch, but things that would be nice to fix up over the next little while: (In approx order of priority)

- [ ] Favicon/icon
- [ ] The footer nav kinda looks lopsided with the reserve button
- [ ] Is it sufficiently clear that the contract widget is for v1? what's our plan for when the v2 widget is ready?
- [ ] Make the tooltip into a vue component
- Anything else?

**Comment by limedaring** [comment]
👍 to all of the above. Goal to get to this before or at least while I'm on the flights back to Toronto.

**Comment by shazow** [comment]
Added a few more. :)

**Comment by shazow** [comment]
Also FYI v2 is now in master.

**Comment by limedaring** [comment]
Re " Logo doesn't look great on a white background (eg in a preview card)"

a) Whoops, yes, I need to make versions of the logo on different backgrounds/branding guide and all that.
b) By preview card, you mean like a Twitter preview card when someone tweets the site, or something else?

**Comment by shazow** [comment]
@limedaring a) No worries. I'm okay without a full branding guide and stuff. :)
b) Yea, things like Twitter/Slack/Messenger previews. Here it is on Facebook Messenger:

![image](https://user-images.githubusercontent.com/6292/44792216-62150900-ab71-11e8-80d5-2efe71af8575.png)

**Comment by limedaring** [comment]
Some followup discussion on ones not marked off yet: 

**" Is it sufficiently clear that the contract widget is for v1? what's our plan for when the v2 widget is ready?"** — I think the contract right now makes that clear by mentioning both mvp and v1? I think this is your call.

**"The footer nav kinda looks lopsided with the reserve button"** — It feels visually evenly weighted to me, personally. The fat input form commands a lot of attention, and the two lists (lighter weight on their own, heavier together) feels visually balanced against the form. Again, your call. :)

**" Copy: Is it clear that this is an OSS project?"** — I don't think that's clear. At least there is a link to the source code in the footer. 

Maybe we could make the description better... what about "Creating a financial marketplace to decentralize the Ethereum network by allowing more people to run full nodes and serve native light clients. Open source, currently in alpha." Which also removes the passive voice too.

**Comment by shazow** [comment]
> Re: "The footer nav kinda looks lopsided with the reserve button"

The way the button is aligned right now, it kinda looks like a header to me rather than something clickable. Not a huge deal though.

> Re: " Copy: Is it clear that this is an OSS project?"

I'd love some copy tweaks. :)
